apiVersion: skaffold/v2alpha3
kind: Config 
deploy: 
  kubectl:  
    manifests: 
      - ./infra/k8s/* 
build:
  local:
    push: false
  artifacts:    
    - image: christapherantony/auth 
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts" 
            dest: .  
    - image: christapherantony/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:  
          - src: '**/*.js'  
            dest: .
    - image: christapherantony/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: . 
    - image: christapherantony/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: . 
     